import 'package:flutter/material.dart';

final Map<String, IconData> myIconCollection = {
    'Event': Icons.calendar_today,
    'Holiday': Icons.airplane_ticket,
    'Flight': Icons.flight_takeoff,
    'Beach': Icons.beach_access,
    'Breakfast': Icons.brunch_dining,
    'Business': Icons.business_center,
    'Birthday': Icons.cake,
    'Celebration': Icons.celebration,
    'Coffee': Icons.coffee,
    'Dining': Icons.dining,
    'Dinner': Icons.dinner_dining,
    'Tea': Icons.emoji_food_beverage,
    'Shopping': Icons.local_mall,
    'Lunch': Icons.fastfood,
    'Gym': Icons.fitness_center,
    'Food': Icons.flatware,
    'Camping': Icons.park,
    'Hiking': Icons.hiking,
    'Breakfast v2.0': Icons.free_breakfast,
    'Golf': Icons.golf_course,
    'Kayaking': Icons.kayaking,
    'Kitesurfing': Icons.kitesurfing,
    'Bar': Icons.liquor,
    'Bar v2.0': Icons.local_bar,
    'Cafe': Icons.local_cafe,
    'Dining v2.0': Icons.local_dining,
    'Grocery': Icons.local_grocery_store,
    'Movie': Icons.local_movies,
    'Shopping v2.0': Icons.local_offer,
    'Food v2.0': Icons.lunch_dining,
    'Movie v3.0': Icons.movie,
    'Bar v3.0': Icons.nightlife,
    'BBQ': Icons.outdoor_grill,
    'Cycling': Icons.pedal_bike,
    'Pets': Icons.pets,
    'Food v4.0': Icons.ramen_dining,
    'Food v5.0': Icons.restaurant,
    'Sailing': Icons.sailing,
    'Shopping v3.0': Icons.shopping_bag,
    'Skateboarding': Icons.skateboarding,
    'bar v3.0': Icons.sports_bar,
    'Baseball': Icons.sports_baseball,
    'Basketball': Icons.sports_basketball,
    'Gaming': Icons.sports_esports,
    'Football': Icons.sports_football,
    'Rugby': Icons.sports_rugby,
    'Soccer': Icons.sports_soccer,
    'Tennis': Icons.sports_tennis,
    'Volleyball': Icons.sports_volleyball,
    'Surfing': Icons.surfing,
    'Movie v2.0': Icons.theaters,
    'Volunteer': Icons.volunteer_activism,
    'Chill': Icons.weekend,
  };